// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wmcheqmipmsyzvamlpqc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndtY2hlcW1pcG1zeXp2YW1scHFjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MTIxNTksImV4cCI6MjA2NTQ4ODE1OX0.gFd8EFeyYpAj3i1TJDD-kh0ZdMP76GGtq3u5h7_M8c8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);